package addon

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/brohd11/gdaddon/internal/source"

	"gopkg.in/ini.v1"
)

// pluginCfgNames are the config filenames that mark an installable addon/library
// and carry its version: plugin.cfg (Godot editor plugins) and version.cfg
// (libraries that are versioned but intentionally don't appear in the plugin
// menu). Both use the same INI shape — a [plugin] section with version="…".
// Centralized here so the recognized set can be changed in one place.
var pluginCfgNames = []string{"plugin.cfg", "version.cfg"}

// pluginCfgPath returns the path of the recognized config file in dir (checked in
// pluginCfgNames order), or "" if none is present.
func pluginCfgPath(dir string) string {
	for _, name := range pluginCfgNames {
		p := filepath.Join(dir, name)
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p
		}
	}
	return ""
}

// hasPluginCfg reports whether dir is an addon/library folder.
func hasPluginCfg(dir string) bool { return pluginCfgPath(dir) != "" }

// intendedVersion is the release identity to record for an install: the canonical
// release tag when set, else the manifest/store version. Used to stamp a synthetic
// version.cfg for packages that ship no config of their own (see stampVersion).
func intendedVersion(a Addon) string {
	if a.Tag != "" {
		return a.Tag
	}
	return a.Version
}

// stampVersion writes a minimal installer-generated version.cfg into dir recording
// ver (the installed version, so getLocalPluginVersion can read it back and Inspect
// can match it — config-less packages like icon packs otherwise read as a perpetual
// "installed unknown" mismatch) and srcURL (the upstream repo it was installed from,
// read back by the Scan action via SourceURL). It is a no-op when dir already carries
// a plugin.cfg/version.cfg (an authored config always wins — never clobber it), when
// dir is a namespace folder holding other plugin folders (it is a level of the layout,
// not an addon), or when there's nothing to record (both ver and srcURL empty, e.g.
// a branch-HEAD install of a store package). Only the keys with a value are emitted. The version
// normalization matches pinInstall's, so the stamped value equals what the manifest
// records. Best-effort: a write error is ignored (this tracking is a convenience).
func stampVersion(dir, ver, srcURL string) {
	if pluginCfgPath(dir) != "" {
		return
	}
	// The mirror case: a folder with no config of its own that *contains* plugin folders
	// is a namespace level (addons/addon_lib), not an addon. Stamping it would make
	// ScanInstalled stop there and never see the real plugin beneath it.
	if len(pluginDirs(dir)) > 0 {
		return
	}
	ver = strings.TrimPrefix(strings.TrimSpace(ver), "v")
	srcURL = strings.TrimSpace(srcURL)
	if ver == "" && srcURL == "" {
		return
	}
	body := "; generated by gdaddon\n[plugin]\n"
	if ver != "" {
		body += "version=\"" + ver + "\"\n"
	}
	if srcURL != "" {
		body += "source=\"" + srcURL + "\"\n"
	}
	_ = os.WriteFile(filepath.Join(dir, "version.cfg"), []byte(body), 0o644)
}

// readPluginCfgKey reads one key from dir's plugin.cfg/version.cfg [plugin] section,
// returning the unquoted, space-trimmed value or "" when the file/section/key is
// absent or unreadable. The silent "" fallback is the behavior every caller relies on
// (an unversioned or dir-less addon is normal, not an error). Callers that need to
// distinguish a read error (e.g. Dependencies) load the config themselves.
func readPluginCfgKey(dir, key string) string {
	cfgPath := pluginCfgPath(dir)
	if cfgPath == "" {
		return ""
	}
	cfg, err := ini.Load(cfgPath)
	if err != nil {
		return ""
	}
	raw := cfg.Section("plugin").Key(key).String()
	return strings.Trim(strings.TrimSpace(raw), `'"`)
}

// installDir reads the installer-specific install-path key an addon may declare in its
// plugin.cfg/version.cfg under addonDir — a project-root-relative install path the
// author can pin (like the custom `deps` key). Either `dir` or `path` names it, `dir`
// winning when both are present; `path` is accepted because authors reach for the same
// word the manifest uses (godot-tree-sitter-gd's version.cfg declares
// path="addons/addon_lib/tree_sitter_gd"). Returns "" when there's no config, neither
// key, or the value is not a project-root-relative path.
//
// That last case is the security-relevant one: this value comes from the *downloaded
// package*, and its destination is os.RemoveAll'd before being written. An absolute
// path or one climbing out with ".." is ignored here — for either key — so the install
// falls back to the normal addons/<name> derivation rather than failing;
// writePlacement's resolveUnder is the hard backstop for anything that reaches it by
// another route.
func installDir(addonDir string) string {
	dir := readPluginCfgKey(addonDir, "dir")
	if dir == "" {
		dir = readPluginCfgKey(addonDir, "path")
	}
	if dir == "" {
		return ""
	}
	if !filepath.IsLocal(filepath.FromSlash(dir)) {
		return ""
	}
	return dir
}

// SourceURL reads the installer-specific `source` key an addon may declare in its
// plugin.cfg/version.cfg under addonDir — the upstream repo it was installed from —
// and returns a canonical repo url, or "" when there's no config, no source key, or
// the value is unparseable. Stamped by stampVersion on install and read back by the
// Scan action to prefill the Track form's url (see Installed.SuggestedURL).
func SourceURL(addonDir string) string {
	return normalizeSource(readPluginCfgKey(addonDir, "source"))
}

// normalizeSource turns a `source` value into a canonical repo url. It accepts a full
// url (https://host/owner/repo[.git], validated and normalized) or owner/repo /
// host/owner/repo shorthand (github.com assumed). Returns "" on anything malformed.
func normalizeSource(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	if strings.Contains(raw, "://") {
		if _, err := source.RepoID(raw); err != nil {
			return ""
		}
		return NormalizeRepoURL(raw)
	}

	_, _, _, url, ok := parseRepoShorthand(raw)
	if !ok {
		return ""
	}
	return url
}

// canonicalRepoURL reduces an install url to its canonical https://host/owner/repo
// form (dropping any .git/.zip/release-asset path), or "" when rawURL isn't a
// recognized repo (a store url or local archive path). Used to stamp `source` into a
// generated version.cfg from the manifest url an addon was installed from.
func canonicalRepoURL(rawURL string) string {
	id, err := source.RepoID(rawURL)
	if err != nil {
		return ""
	}
	return "https://" + id
}
