package addon

import (
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/ini.v1"
)

// pluginCfgNames are the config filenames that mark an installable addon/library
// and carry its version: plugin.cfg (Godot editor plugins) and version.cfg
// (libraries that are versioned but intentionally don't appear in the plugin
// menu). Both use the same INI shape — a [plugin] section with version="…".
// Centralized here so the recognized set can be changed in one place.
var pluginCfgNames = []string{"plugin.cfg", "version.cfg"}

// pluginCfgPath returns the path of the recognized config file in dir (checked in
// pluginCfgNames order), or "" if none is present.
func pluginCfgPath(dir string) string {
	for _, name := range pluginCfgNames {
		p := filepath.Join(dir, name)
		if info, err := os.Stat(p); err == nil && !info.IsDir() {
			return p
		}
	}
	return ""
}

// hasPluginCfg reports whether dir is an addon/library folder.
func hasPluginCfg(dir string) bool { return pluginCfgPath(dir) != "" }

// intendedVersion is the release identity to record for an install: the canonical
// release tag when set, else the manifest/store version. Used to stamp a synthetic
// version.cfg for packages that ship no config of their own (see stampVersion).
func intendedVersion(a Addon) string {
	if a.Tag != "" {
		return a.Tag
	}
	return a.Version
}

// stampVersion writes a minimal installer-generated version.cfg into dir recording
// ver, so getLocalPluginVersion can read the installed version back and Inspect can
// match it — config-less packages (icon packs, asset libraries) otherwise read as a
// perpetual "installed unknown" mismatch. It is a no-op when ver normalizes to ""
// (nothing to record, e.g. a branch-HEAD install) or when dir already carries a
// plugin.cfg/version.cfg (an authored config always wins — never clobber it). The
// normalization matches pinInstall's, so the stamped value equals what the manifest
// records. Best-effort: a write error is ignored (version tracking is a convenience).
func stampVersion(dir, ver string) {
	ver = strings.TrimPrefix(strings.TrimSpace(ver), "v")
	if ver == "" || pluginCfgPath(dir) != "" {
		return
	}
	body := "; generated by gdaddon\n[plugin]\nversion=\"" + ver + "\"\n"
	_ = os.WriteFile(filepath.Join(dir, "version.cfg"), []byte(body), 0o644)
}

// readPluginCfgKey reads one key from dir's plugin.cfg/version.cfg [plugin] section,
// returning the unquoted, space-trimmed value or "" when the file/section/key is
// absent or unreadable. The silent "" fallback is the behavior every caller relies on
// (an unversioned or dir-less addon is normal, not an error). Callers that need to
// distinguish a read error (e.g. Dependencies) load the config themselves.
func readPluginCfgKey(dir, key string) string {
	cfgPath := pluginCfgPath(dir)
	if cfgPath == "" {
		return ""
	}
	cfg, err := ini.Load(cfgPath)
	if err != nil {
		return ""
	}
	raw := cfg.Section("plugin").Key(key).String()
	return strings.Trim(strings.TrimSpace(raw), `'"`)
}
